# version: '3.9'

services:
  mysql_db:
    container_name: mysql_db
    image: mysql:8.0
    ports:
      - "3307:3306"
    restart: always
    command: --secure-file-priv=""
    environment:
      DB_SECRET_PASSWORD: ${DB_SECRET_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_SECRET_PASSWORD}
      MYSQL_DATABASE: money_manager_db
    volumes:
      - mysql_data:/var/lib/mysql
      - C:\Users\Usuario\Desktop\Data Analysis Coursera\MySQL Uploads:/export
  api:
    image: nodeapp
    ports:
      - 3030:3030
    depends_on:
      - mysql_db
    environment:
      - DB_SECRET_PASSWORD=${DB_SECRET_PASSWORD}

volumes:
  mysql_data: {}
